"""
Zillow ZHVI (Home Value Index) lookup by ZIP code.
Used to override Census ACS median home values that are capped at $2,000,001,
and to provide price velocity signals for Up-and-Coming neighborhood detection.

Data: data/zillow_zhvi_zip.json — generated by scripts/baselines/build_zillow_zhvi.py
Rebuild: PYTHONPATH=. python3 scripts/baselines/build_zillow_zhvi.py

JSON structure:
  values           — middle-tier current ZHVI (existing usage, Census cap override)
  bottom_tier      — bottom-tier current ZHVI
  appreciation_1yr — middle-tier 1yr % change (e.g. 0.082 = +8.2%)
  appreciation_3yr — middle-tier 3yr % change
  velocity_6mo     — bottom-tier 6mo % change (momentum signal; bottom tier reprices first)
"""

import json
import os
from typing import Optional

_CACHE: Optional[dict] = None
CENSUS_CAP = 2_000_001


def _load() -> dict:
    global _CACHE
    if _CACHE is None:
        path = os.path.join(os.path.dirname(__file__), '..', 'data', 'zillow_zhvi_zip.json')
        with open(os.path.normpath(path)) as f:
            _CACHE = json.load(f)
    return _CACHE


def get_zhvi(zip_code: str) -> Optional[int]:
    """Return Zillow middle-tier ZHVI for a ZIP code, or None if not found."""
    if not zip_code:
        return None
    data = _load()
    return data['values'].get(zip_code.zfill(5))


def get_zhvi_velocity(zip_code: str) -> dict:
    """
    Return price velocity signals for a ZIP code.

    Returns dict with keys:
      appreciation_1yr  — middle-tier 1yr % change (float or None)
      appreciation_3yr  — middle-tier 3yr % change (float or None)
      velocity_6mo      — bottom-tier 6mo % change (float or None); primary momentum signal
      bottom_tier_value — bottom-tier current ZHVI (int or None)
    """
    if not zip_code:
        return {'appreciation_1yr': None, 'appreciation_3yr': None,
                'velocity_6mo': None, 'bottom_tier_value': None}
    z = zip_code.zfill(5)
    data = _load()
    return {
        'appreciation_1yr':  data.get('appreciation_1yr', {}).get(z),
        'appreciation_3yr':  data.get('appreciation_3yr', {}).get(z),
        'velocity_6mo':      data.get('velocity_6mo', {}).get(z),
        'bottom_tier_value': data.get('bottom_tier', {}).get(z),
    }


def get_home_value(census_value: Optional[int], zip_code: Optional[str]) -> tuple[Optional[int], bool]:
    """
    Return (home_value, zillow_used).
    Uses Zillow when Census hits its $2,000,001 cap and a Zillow value is available.
    """
    if census_value == CENSUS_CAP and zip_code:
        zhvi = get_zhvi(zip_code)
        if zhvi and zhvi > CENSUS_CAP:
            return zhvi, True
    return census_value, False
